# Generated by Django 4.0.3 on 2022-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_clothes_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
