# Generated by Django 4.0.3 on 2022-04-04 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_clothes_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shoes_type', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Sandals', 'Sandals'), ('High Heels', 'High Heels'), ('Flip Flops', 'Flip Flops'), ('Running Shoes', 'Running Shoes')], default='Sneakers', max_length=13)),
                ('suitable_for', models.CharField(choices=[('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Spring', 'Spring')], default='Summer', max_length=6)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shoes',
            },
        ),
    ]
