# Generated by Django 4.0.3 on 2022-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
